### ISSUE TITLE
Classical Mythology 2015-- Hypothes.is workflow

### ISSUE THREAD

**Issue by Marie-ClaireBeaulieu** [perseids-project/perseids_docs#295] opened 2015-09-01 14:25 UTC
Starting discussion about adapting the Hypothes.is workflow from JOTH and Visible Words for Myth class this fall as per discussion between @balmas and myself

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-01 14:32
I want to revisit the hypothesis instructions for the myth class. As per conversation with balmas, it was decided to create a new wiki page based on the one for JOTH, and that questions would be tracked in this issue,

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-01 14:38
@PonteIneptique and @balmas : should hypothes.is annotations created in the context of this class keep the tag JOTH? 

@PonteIneptique : I will rework the decision graph you made for Visible Words for this, unless you tell me otherwise. As you know, I want to add attestations on top of persons and relationships

**Comment by balmas** [comment] 2015-09-03 00:03
1) tag: the mapping algorithm uses this tag to determine the rules for enforcing validity and mapping the details of the hypothes.is annotation to the stable identifiers and OA structure.  As JOTH used a slightly different approach we probably don't want to reuse that tag here. Currently the 2 mapping schemes we have used are identified by either 'joth' or 'visiblewords'. I think there is value in having a project-specific tag like this, but I'd like to see if we could get away from having to rewrite the rules for each project.  So maybe we could come up with a general purpose based upon the type of annotation?  Maybe something like 'perseids-sn' for perseids social network?

2) graph -- I think we can reuse the visible words graph, but we should probably talk about the stable identifiers you want to use for the person identifiers. Are we going to continue with the Smith identifiers as we did for JOTH or are we going to use the LGPN like for visible words?  Or both? Or neither?

3) attestations -- I believe the graph already has instructions for attestations so I'm not sure if those instructions need to change or not.

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-07 17:34
@balmas 
1) ok. How about the tag "PSN". Keeping them short makes life easy, as Hypothes.is can be slow to type in
2) I think we should keep the stable identifiers from Smith, as we are continuing that work.
3) Will look into attestations right now
4) @PonteIneptique : I'm wondering if it would be possible to tag characters as "mortal" and "immortal", and color-code that in the graph (or possibly boldface for immortals or something like that)

**Comment by PonteIneptique** [comment] 2015-09-07 17:38
@Marie-ClaireBeaulieu 4) Eventually yes, given the fact we find the ontology for it. We should just find where to add that and if we add a proof about it (attestation of immortality ?)

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-07 17:42
@PonteIneptique : thanks. this idea of an attestation of immortality is interesting, because some figures are mortal in some sources, immortal in others. But that gets us into a whole another layer of data, so possibly something for students to work on next year? They could take all the existing annotations at that point, we can come up with the workflow, and have them add that info?

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-07 17:59
@balmas @PonteIneptique : as data continues to be added, we are going to have to enhance navigation in the display. We can already navigate by place from the front page, but it would be nice to have an index of characters, and to have the entries organized alphabetically in the reading view.

**Comment by PonteIneptique** [comment] 2015-09-07 18:03
@Marie-ClaireBeaulieu The current view for JOTH should not be taken as something we want to work on. Probably @balmas will disagree but I think the current technical stack is not in favour of building on it.

It should be restarted and giving time to it.

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-07 18:41
@PonteIneptique @balmas @annakrohn @TDBuck : wiki edited at http://perseids.org/sites/joth/#book/urn:cts:pdlrefwk:viaf88890045.003.perseus-eng1/read/urn:cts:pdlrefwk:viaf88890045.003.perseus-eng1:S.scylla_1

Please take a look, especially at the attestations instructions, which I got from Anna's work here:  https://drive.google.com/folderview?id=0Byqi9oOaJg2gfmtfRFhWTEdqWENhT2lyUG5QS09RRUpRVjNZRGlqejROU016MVFDNXFCUE0&usp=sharing. I will use Anna's materials to introduce Greek and Latin and do the word study exercise in order to have students find attestations. Given the fact that Smith is already giving us the references to the different versions of stories and so on, I think the attestations exercise is very valuable in enhancing the resource with the vocabulary used to describe the figure (that info is absent from Smith)

**Comment by balmas** [comment] 2015-09-08 13:00
Before I comment on the instructions I want to be sure I understand the expected end result in terms of the data. In natural language,  I believe what are asking the students to do is the following:

1) link the Smiths' text to the stable identifier for the person who is the subject of the entry
2) link any occurrences of person names in the Smith's entry to the stable identifiers for the people represented by those names
3) assert all the interpersonal relationships identified in the texts as graphs using the SNAP ontologie
4) assert the text of the Smith's entry which identifies these relationships as attestations to the relationships
5) link any occurrences of place  names in the Smith's entry to their stable identifiers in Pleiades
6) assert attestations to the people mentioned in the Smith's entries from other textual sources on Perseus

Is that right?

**Comment by balmas** [comment] 2015-09-08 13:57
And then in terms of visualization of this data, we want:

1) to be able to browse the Smith's text, by entry, with each page displaying alongside the text a visualization of 
 -- the people mentioned in the text
 -- the relationships identified in the text 
-- the places mentioned in the text
-- attestations from other sources to the people mentioned in the text
2) browse an alternate index, by person name, from which you can access the page or pages on which the person is either (a) the subject, or (b) mentioned

**Comment by balmas** [comment] 2015-09-08 14:39
And in terms of specific changes to the existing JOTH Gap-Vis based visualization, the following should be noted:

1) we want the place index to be able to deal with entries for multiple people (e.g. Rome bring you to not only Romulus but any other entries mentioning Romulus ?)

2) we want to be able to visual the social network in different forms -- i.e. circular makes sense when we are focusing on the subject of a smith's entry, but other visualizations would be useful as well

**Comment by balmas** [comment] 2015-09-08 14:40
And for priorities for this semester:

1) Priority 1
-  make sure the data identified above can be captured correctly
- make sure the data can be visualized with the current JOTH visualiation
2) Priority 2
- improvements/enhancements to displays (may need to wait until next year though)

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-08 14:43
All of this sounds good, I would just change the following:

1) we want the place index to be able to deal with entries for multiple people (e.g. Rome bring you to not only Romulus but any other entries mentioning Romulus ?)

1) we want the place index to show entries for multiple people (e.g. Rome would bring you to everyone who has been annotated as being at Rome, like Romulus, Tarpeia, Remus, Aeneas, etc.)

**Comment by balmas** [comment] 2015-09-08 18:14
Annotation Workflow: http://www.gliffy.com/go/publish/image/8865223/L.png

**Comment by balmas** [comment] 2015-09-08 19:04
Ok, I've updated the instructions. We will have to finalize the details of where to find the smith's entries to annotate based upon what happens with hypothes.is but everything else should be mostly okay. Please take a look and let me know. I clarified the workflow, made some adjustments to instruction text, and linked workflow steps to instruction text. It might still need a little cleanup but the technical bits should be right.

I think the next step would be to have you or your TA walk through it step by step to make sure it works and give me sample annotations so that I can make the necessary adjustments to the hypothes.is conversions, as they are a little different than we did before.

If you can tell me one of the entries you want to work with, I will create a static page for it to use for the annotation.

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-08 19:27
thanks Bridget. I have asked my TAs to look through the workflow, but I'd rather be the one to try it out just now. Can you make me a static page for Glaucus: http://www.perseus.tufts.edu/hopper/text?doc=glaucus-bio-1&fromdoc=Perseus%3Atext%3A1999.04.0104. Will try to get to it as soon as possible, definitely over the weekend

**Comment by balmas** [comment] 2015-09-08 20:32
You can use this page for now:
http://www.perseids.org/sites/smiths/glaucus-bio-1.html

This isn't how the static pages will actually look, this is just a quick copy I made of the Perseus page for the purpose of this test.

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-09 19:39
Going through the workflow:

Select a subject Smith's Dictionary Entry: one will be assigned

Locate the stable id of the person resource and add it to the annotation: "annotation body" or "add it in the annotation body"

After Set annotation to public: save

In step 4: Locate the Stable CTS URN identifier for the bibliographic reference and add it to the annotation: in most cases, they can just open the link to Perseus that is provided in Smith's text, and get to the citation URI that way

In step 5: 

Highlight the text indicating the person name
Locate the Stable CTS URN identifier for the characterization reference and add it to the annotation
Between these two steps, we should explain that they need to search the person's name on Perseus and find characterizations. 
On Perseus, use the top right hand corner search box to search for your mythological figure's name.
Beware of homonyms! Many figures share the same name in ancient mythology.

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-12 17:30
@balmas : I updated the instructions as per my comments above. The one item that remains is the following:

!!!EXACT INSTRUCTIONS FOR SELECTING CHARACTER AND FINDING PAGE TBD!!!

I will assign the deities for each team of students, so if you want a list, I can provide that right away for the purpose of producing static pages, if that is the route we go, and then I can go ahead and update the instructions for that

@TDBuck : could you please try this workflow? You can use the same static page I did: http://www.perseids.org/sites/smiths/glaucus-bio-1.html. When you turn on hypothes.is, you will see that I already created 6 annotations, but I would like to know if you find any issues with the instructions or workflow as you go through the process. I may be a bit too familiar with it to see these issues at this point.

**Comment by balmas** [comment] 2015-09-13 22:26
@Marie-ClaireBeaulieu Yes, I think we will have to go with the static page solution as I haven't heard anything more from the hypothes.is team.  Please send me the list and I will deploy the pages and update the instructions.

**Comment by balmas** [comment] 2015-09-14 01:22
@Marie-ClaireBeaulieu we need to change the instructions for the characterization slightly - I need the students to explicitly state the language of the text and the translation and put them each on a separate line. hypothes.is weirdly merged the greek and english text in your annotation and it will be best if we can be explicit. I will update the wiki page to show what I mean.

**Comment by balmas** [comment] 2015-09-14 01:34
@Marie-ClaireBeaulieu another point about the characterization annotations -- in your annotation at https://hypothes.is/a/rtb8T_WnQWCu5z4ue5zv8A you didn't include the CTS reference of the text from which you pulled the text of the characterization. I've updated the instructions to try to make this step clearer. Let me know if you have additional questions about this.

**Comment by balmas** [comment] 2015-09-14 13:16
Sorry, back on the characterizations, as I try to make the data transform for this make sense. @Marie-ClaireBeaulieu am I right that these students aren't necessarily going to be understanding the Greek/Latin themselves and will just be using the translation supplied by Perseus? I think it would be much better if the data in the annotations could be as explicit as possible about the source of the text and translation, and leverage the CTS references here.  I.e. is there any reason we couldn't ask them to do something like this:

1) copy the Citation URI from the Perseus page on which they've found the text.
E.g.
http://data.perseus.org/citations/urn:cts:greekLit:tlg0099.tlg001.perseus-eng1:9.2.23

2) Append the actual text they want to reference to this, separating with an @

E.g.
http://data.perseus.org/citations/urn:cts:greekLit:tlg0099.tlg001.perseus-eng1:9.2.23@torn to pieces

3) copy this full URI into the body of the annotation

4) put the the source text in focus

5) Copy the Citation URI of the source text

E.g
http://data.perseus.org/citations/urn:cts:greekLit:tlg0099.tlg001.perseus-grc1:9.2.23

6) find the Greek (or Latin) text that they want to reference, appending it to the URI separating with an @ 

E.g. http://data.perseus.org/citations/urn:cts:greekLit:tlg0099.tlg001.perseus-grc1:9.2.23@διασπασθέντα

This is much easier for me to transform, and might be easier to explain the logic of to the students as well.

**Comment by balmas** [comment] 2015-09-15 18:53
@Marie-ClaireBeaulieu note also that I've added a clarifying instruction about the order of the relationship. @PonteIneptique had noticed that we actually recorded the original JOTH annotations in the wrong order.  When annotating an entry in Smiths' the subject of the Smith's entry is the main subject of the relationship, so the keyword chosen needs to reflect that.

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-15 19:27
@balmas : I added an example in the characterizations where you explain how to insert the words and translations: example: grc: καλός
                                      eng: beautiful

Is this correct, or do they need to add quotation marks?

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-15 19:33
@balmas : re giving the URI of the text they want to reference in the characterization, that's fine
Updating the instructions now

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-15 20:07
List of deities:

Zeus 
Hera
Poseidon
Hades
Demeter
Hestia
Aphrodite
Dionysus
Hermes
Hephaestus
Ares
Athena
Artemis
Apollo
Leto
Pan
Aeolus
Boreas
Thetis
Ocean
Tethys
Nereus
Proteus
Amphitrite 25
Hypnos
Thanatos
Himeros
Erinyes
Selene
Helios

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-15 20:30
@balmas : the list is this long because we're over-enrolled! 85 students, and I wasn't going to turn a single one down!

Sadly, it seems that hypothes.is is not letting me edit annotations anymore. If I create one, then save it, then open it to edit and try to save again, I get a 401 error, saying that I can't change the group of an annotation (?!) Am I the only one in this situation?

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-15 20:40
@balmas : can you OK my set of annotations on Glaucus and include the link somewhere in the instructions as an example ? http://www.perseids.org/sites/smiths/glaucus-bio-1.html

I think it will be good for students to see a full set of annotations

**Comment by balmas** [comment] 2015-09-15 22:57
hmm @Marie-ClaireBeaulieu I was able to edit my hypothes.is annotation. Are you using the Chrome extension or Firefox?  Were you definitely logged in to hypothes.is with the same account you used to create it?

**Comment by balmas** [comment] 2015-09-16 01:01
@Marie-ClaireBeaulieu I can confirm that all your Glaucus annotations are correct!

**Comment by balmas** [comment] 2015-09-16 01:01
@Marie-ClaireBeaulieu I can confirm that all your Glaucus annotations are correct!

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-16 14:21
@balmas : whohoo on the correct annotations!

As for editing the Hypothes.is annotations, I'm using the Chrome extension, and I'm quite sure I was logging in with the same account since I only have one, but that seems to be moot now as it is letting me edit and save again just fine....

**Comment by TDBuck** [comment] 2015-09-16 14:40
I tired out making some annotations last night, but wasn't sure which board to submit them to for testing purposes. 

Also, definitely feel foolish on this one, I cannot for the life of me find the instructions for this workflow. I can find the visualization that @balmas linked in here, but nothing that looks like something you would hand to students. 

Definitely late to the party on this one.

**Comment by balmas** [comment] 2015-09-16 14:54
@Marie-ClaireBeaulieu Which Smith entry is "Erinyes" ? I see erinnyes, but it doesn't have any text, just points at EUMENIDES

**Comment by balmas** [comment] 2015-09-16 14:54
@TDBuck the instructions are here: https://github.com/perseids-project/perseids_docs/wiki/Hypothes.is-annotations-for-Classical-Mythology-2015

**Comment by balmas** [comment] 2015-09-16 16:47
The links to the static pages are here:

http://perseids.org/sites/smiths/

I will update the instructions, but @Marie-ClaireBeaulieu and @TDBuck can you please check these out to be sure they are all right?

@Marie-ClaireBeaulieu in addition to needing more info on Erinnyes, I need it for Hypnos, because that entry is also empty.

**Comment by balmas** [comment] 2015-09-16 17:04
I have updated the instructions with regard to where to find the pages to annotate, and the smith's stable identifiers. It might still be a little confusing. Please fix as you see fit!

**Comment by balmas** [comment] 2015-09-16 17:34
The updated mapping code is now live. The preview of the Glaucus annotations from both of you will still fail because they aren't using the final URL that I devised for the static pages .. sorry about that. You can now find Glaucus at http://perseids.org/sites/smiths/G/glaucus_1.html

I did a few annotations quickly and they seem to work. I don't have place or characterization here.

http://sosol.perseids.org/sosol/publications/14122/oa_cite_identifiers/24101/preview

**Comment by balmas** [comment] 2015-09-16 17:43
oh, one other note on the gods. @Marie-ClaireBeaulieu the entry for aeolus is a little weird it has all 3 aeolus in one entry, rather than separating them out.  Whichever student has this might need a little instruction as to which one to annotate.

**Comment by TDBuck** [comment] 2015-09-16 17:49
Is it too late to change the gods? Should we chuck the ones that might be strange/empty/broken/difficult and instead do others? @Marie-ClaireBeaulieu

**Comment by balmas** [comment] 2015-09-16 17:52
It's not too late

**Comment by TDBuck** [comment] 2015-09-16 18:02
@balmas Try out Prometheus, Persephone, and Cronus (a little on the short side) to see if those are more what you are looking for. They are certainly more direct since you would only be talking about one mythological person. I can poke around Smith some more and find some others, but the loading times are killing me.

**Comment by balmas** [comment] 2015-09-16 18:06
I will defer to MC on which to choose, as it's her syllabus.

**Comment by balmas** [comment] 2015-09-16 18:11
For posterity's sake, here's what I did to produce the static pages.

I used the version of Smith's that's in the PerseusDL/canonical-pdlrefwk repo.

This is loaded in a CTS 5 endpoint at http://services2.perseids.org/exist/restxq/cts?request=GetValidReff&inv=annotsrc&urn=urn:cts:pdlrefwk:viaf88890045.003.perseus-eng1

I used a slightly modified version of the standard TEI html5 transformation at https://github.com/PerseusDL/tei-conversion-tools/tree/master/cts/xslt.

The results are deployed on perseids.org in /usr/local/sites/smiths, directories named according to alphabetic entry letter and files named per entity id.  This is served e.g. at http://perseids.org/sites/smiths/Z/zeus_1.html etc.   The HTML references the standard TEI 5 css plus additional styles defined in https://github.com/PerseusDL/tei-conversion-tools/tree/master/cts/css (also deployed on perseids.org).

The Hypothesis transformation was updated for the new mapping rules as all discussed above. It also parses the path of the html file used for annotation to construct the CTS urn and the stable person identifier. This is a bit stupid now because this information is all available on the page, and we could have deployed on urls that corresponded to the URNs, but it was based upon the original P4-based workflow which I was trying to tweak as little as possible, as hopefully this will be the last time we do it this way.

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-16 19:12
@balmas : Prometheus, Persephone, and Cronus are fine by me. We can replace Erinnyes with Eumenides (those are the same divinities, they just go by different names). Hypnos should be replaced by Somnus (that's just his Latin name, apparently Smith is not very consistent on using Latin or Greek names for gods). Aeolus is definitely a weird one, but it's OK to keep him, I can coach the team who end up with him.

@TDBuck : thanks for your help :-)

**Comment by balmas** [comment] 2015-09-16 21:02
replacements and additions made.  Shall we close this item now?

**Comment by Marie-ClaireBeaulieu** [comment] 2015-09-17 12:29
Thanks @balmas ! Yep, I think we're ready to close, unless @TDBuck has anything to add?

**Comment by TDBuck** [comment] 2015-09-17 12:52
Nope. I'm all set.

**Comment by balmas** [comment] 2015-09-17 12:53
Closing!

**Comment by Marie-ClaireBeaulieu** [comment] 2015-10-21 07:48
@balmas 
Grading first round of annotations. This team did not follow instructions and used the Smith page in Perseids rather than the static page. http://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.04.0104:entry=selene-bio-1&highlight=

Should I tell them to redo their annotations on the static page?

**Comment by balmas** [comment] 2015-10-21 13:05
Hi @Marie-ClaireBeaulieu I would guess they are failing the conversion? If so, then the best thing would be to ask them to redo them.

**Comment by Marie-ClaireBeaulieu** [comment] 2015-10-22 12:46
thanks @balmas . I asked them to redo it.

**Closed** 2015-11-02 18:36 UTC
